language: android
jdk:
  - oraclejdk8
env:
  global:
    - MIN_SDK_VERSION=android-15
    - TARGET_SDK_VERSION=android-22
  matrix:
    - SYS_IMG=armeabi-v7a
android:
  components:
    # Tools.
    - build-tools-22.0.0
    - build-tools-22.0.1
    - platform-tools
    - tools

    # Build matrix.
    - $MIN_SDK_VERSION
    - $TARGET_SDK_VERSION
    - sys-img-$SYS_IMG-$TARGET_SDK_VERSION

    # Additional components.
    - extra-android-m2repository
    - extra-android-support
before_script:
  # Create, start and wait for emulator.
  - chmod u+x android-wait-for-emulator
  - echo no | android create avd --force -n test -t $MIN_SDK_VERSION --abi $SYS_IMG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

  # Prepare gradle script.
  - chmod u+x gradlew
