language:
  - java
jdk:
  - oraclejdk7
  - openjdk7
env:
  global:
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_BUILD_TOOLS_VERSION=19.0.1
    - ANDROID_COMPILE_SDK_VERSION=19
    - ANDROID_MIN_SDK_VERSION=15
    - ANDROID_TARGET_SDK_VERSION=19
    - ANDROID_SDK_TGZ=android-sdk_r22-linux.tgz
  matrix:
    - ANDROID_SDK_VERSION=19  ANDROID_SYSTEM_IMAGE_PACKAGE=41
    - ANDROID_SDK_VERSION=18  ANDROID_SYSTEM_IMAGE_PACKAGE=43
    - ANDROID_SDK_VERSION=17  ANDROID_SYSTEM_IMAGE_PACKAGE=45
    - ANDROID_SDK_VERSION=16  ANDROID_SYSTEM_IMAGE_PACKAGE=48
    - ANDROID_SDK_VERSION=15  ANDROID_SYSTEM_IMAGE_PACKAGE=51
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/$ANDROID_SDK_TGZ
  - tar xzf $ANDROID_SDK_TGZ
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/build-tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools

  # Install required Android components.
  - echo y | android update sdk --all --force --no-ui --filter android-$ANDROID_COMPILE_SDK_VERSION,android-$ANDROID_MIN_SDK_VERSION,android-$ANDROID_TARGET_SDK_VERSION,android-$ANDROID_SDK_VERSION
  - echo y | android update sdk --all --force --no-ui --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION,platform-tools,extra-android-support
  - echo y | android update sdk --all --force --no-ui --filter $ANDROID_SYSTEM_IMAGE_PACKAGE

  # Create and start emulator
  - echo no | android create avd --force -n test -t android-$ANDROID_SDK_VERSION --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

  # Enabling execution for gradlew and emulator listener
  - chmod +x gradlew
  - chmod +x wait_for_emulator
before_script:
  # Make sure the emulator has started before running tests
  - ./wait_for_emulator
